baseurl = "/"
languageCode = "en-us"
title = "Lazar!!"
theme = "hugo-theme-casper"
disqusShortname = "lazar"
disqus = "https://lazarmarlin.tk"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-136072375-1"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "A website for my homework, fun, and my favorite things."
  cover = "images/cover.jpg"
  author = "Eleazar Allen "
  authorlocation = "Freeport Grand Bahama"
  authorwebsite = "https://lazarmarlin.gq"
  authoremail = "bluemarlin1134@vivaldi.net"
  bio= "Hi, I'm a progammer/hacker, who is homeschooled, and has so much homework, he built a website for it all."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/lazarmarlin/UkSh"
  githubName = "Bluemarlin1134"
  #twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  sectionPagesMenu = "main"
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"

[[menu.main]]
  name = "ğŸ”¬ Science!! ğŸ§ "
  weight = 2
  identifier = "Science"
  url = "https://science.lazarmarlin.tk"
  
  
[[menu.main]]
  name = "Back Home ğŸ¡"
  weight = 1
  identifier = "Home"
  url = "https://lazarmarlin.tk"

[[menu.main]]
  name = "ğŸ›© ğŸ›³ My Travel Journal ğŸ—»"
  weight = 9
  identifier = "travel"
  url = "https://travel.lazarmarlin.tk"

[[menu.main]]
  name = "â–ğŸ’²Math â— â•"
  weight = 10
  identifier = "math"
  url = "https://math.lazarmarlin.tk"
  
  
 [[menu.main]]
  name = "ğŸ˜€ Language!! ğŸ˜ƒ"
  weight = 10
  identifier = "lan"
  url = "https://language.lazarmarlin.tk"
  
 [[menu.main]]
  name = "Chloe!!"
  weight = 14
  identifier = "clo"
  url = "https://chloe.lazarmarlin.tk"
