baseurl = "/"
languageCode = "en-us"
title = "Chloe!!"
theme = "hugo-theme-casper"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Hello!"
  cover = "images/cover.jpg"
  author = "Lazar Marlin "
  authorlocation = "Freeport Grand Bahama"
  authorwebsite = "https://lazarmarlin.gq"
  bio= "Hi, you don't remember me?"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "Bluemarlin1134"
  #twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  sectionPagesMenu = "main"
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
