baseurl = "/"
languageCode = "en-us"
title = "Lazar!!"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "A website for my homework, fun, and my favorite things."
  cover = "images/cover.jpg"
  author = "Eleazar Allen "
  authorlocation = "Freeport Grand Bahama"
  authorwebsite = "https://lazarmarlin.gq"
  authoremail = "bluemarlin1134@vivaldi.net"
  bio= "Hi, I'm a progammer/hacker, who is homeschooled, and has so much homework, he built a website for it all."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/lazarmarlin/UkSh"
  githubName = "Bluemarlin1134"
  #twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  sectionPagesMenu = "main"
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"

[[menu.main]]
  name = "Just Science!"
  weight = 1
  identifier = "Science"
  url = "https://science.lazarmarlin.tk"
  
  
[[menu.main]]
  name = "Chloe!!"
  weight = 8
  identifier = "chloe"
  url = "https://chloe.lazarmarlin.tk"
